import { useRef } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Download, Share2, FileText, Copy, Check } from "lucide-react";
import { GradeData } from "@/types/grades";
import { toast } from "@/hooks/use-toast";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";
import { useState } from "react";

interface ExportPanelProps {
  courses: GradeData[];
  totalCredits: number;
  totalGradePoints: number;
  sgpa: number;
  resultRef: React.RefObject<HTMLDivElement | null>;
}

export function ExportPanel({
  courses,
  totalCredits,
  totalGradePoints,
  sgpa,
  resultRef,
}: ExportPanelProps) {
  const [isExporting, setIsExporting] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleExportPDF = async () => {
    if (!resultRef.current) return;

    setIsExporting(true);
    try {
      const canvas = await html2canvas(resultRef.current, {
        scale: 2,
        backgroundColor: "#ffffff",
        useCORS: true,
      });

      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

      const imgWidth = 190;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;

      pdf.setFillColor(139, 92, 246);
      pdf.rect(0, 0, 210, 15, "F");
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(14);
      pdf.text("SGPA Calculator - Grade Report", 105, 10, { align: "center" });

      pdf.addImage(imgData, "PNG", 10, 20, imgWidth, imgHeight);

      pdf.setTextColor(100, 100, 100);
      pdf.setFontSize(8);
      pdf.text(
        `Generated on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`,
        105,
        290,
        { align: "center" }
      );

      pdf.save(`SGPA_Report_${new Date().toISOString().split("T")[0]}.pdf`);

      toast({
        title: "PDF Exported!",
        description: "Your grade report has been downloaded.",
      });
    } catch (error) {
      console.error("Export error:", error);
      toast({
        title: "Export Failed",
        description: "Could not generate PDF. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsExporting(false);
    }
  };

  const handleCopyResults = () => {
    const text = `SGPA Report
================
SGPA: ${sgpa.toFixed(2)}
Total Credits: ${totalCredits}
Total Grade Points: ${totalGradePoints}

Courses:
${courses
  .map(
    (c) =>
      `- ${c.courseCode || "N/A"} | ${c.courseName} | Credits: ${c.credits} | Grade: ${c.grade} | Points: ${c.gradePoints}`
  )
  .join("\n")}

Generated by SGPA Calculator`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);

    toast({
      title: "Copied!",
      description: "Results copied to clipboard.",
    });
  };

  const handleShare = async () => {
    const shareData = {
      title: "My SGPA Report",
      text: `I scored an SGPA of ${sgpa.toFixed(2)}! Calculated using SGPA Calculator.`,
      url: window.location.href,
    };

    if (navigator.share) {
      try {
        await navigator.share(shareData);
      } catch (error) {
        // User cancelled or error
        handleCopyResults();
      }
    } else {
      handleCopyResults();
    }
  };

  // Save to localStorage
  const handleSave = () => {
    const savedResults = JSON.parse(localStorage.getItem("sgpa-results") || "[]");
    const newResult = {
      id: Date.now(),
      date: new Date().toISOString(),
      courses,
      totalCredits,
      totalGradePoints,
      sgpa,
    };
    savedResults.unshift(newResult);
    localStorage.setItem("sgpa-results", JSON.stringify(savedResults.slice(0, 10)));

    toast({
      title: "Saved!",
      description: "Results saved to your browser.",
    });
  };

  return (
    <Card className="border-border/50 bg-card/50 backdrop-blur-sm shadow-lg animate-fade-up">
      <CardHeader className="pb-4">
        <CardTitle className="flex items-center gap-2 text-xl">
          <FileText className="w-5 h-5 text-primary" />
          Export & Save
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          <Button
            variant="outline"
            onClick={handleExportPDF}
            disabled={isExporting || courses.length === 0}
            className="gap-2 hover:bg-primary hover:text-primary-foreground transition-colors"
          >
            <Download className="w-4 h-4" />
            PDF
          </Button>
          <Button
            variant="outline"
            onClick={handleCopyResults}
            disabled={courses.length === 0}
            className="gap-2 hover:bg-secondary hover:text-secondary-foreground transition-colors"
          >
            {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            Copy
          </Button>
          <Button
            variant="outline"
            onClick={handleShare}
            disabled={courses.length === 0}
            className="gap-2 hover:bg-accent hover:text-accent-foreground transition-colors"
          >
            <Share2 className="w-4 h-4" />
            Share
          </Button>
          <Button
            onClick={handleSave}
            disabled={courses.length === 0}
            className="gap-2 bg-gradient-to-r from-primary to-secondary hover:opacity-90"
          >
            <FileText className="w-4 h-4" />
            Save
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
